apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  tlsEnabled: false
  resources:
    requests:
      # This is intentionally low to make it work on local kind clusters.
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 2
      memory: 8Gi
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v21.1.7
  nodes: 1
# apiVersion: crdb.cockroachlabs.com/v1alpha1
# kind: CrdbCluster
# metadata:
#   # this translates to the name of the statefulset that is created
#   name: cockroachdb
# spec:
#   dataStore:
#     pvc:
#       spec:
#         accessModes:
#           - ReadWriteOnce
#         resources:
#           requests:
#             storage: "60Gi"
#         volumeMode: Filesystem
#   resources:
#     requests:
#       # This is intentionally low to make it work on local kind clusters.
#       cpu: 500m
#       memory: 2Gi
#     limits:
#       cpu: 2
#       memory: 8Gi
#   tlsEnabled: false
# # You can set either a version of the db or a specific image name
# # cockroachDBVersion: v21.1.7
#   image:
#     name: cockroachdb/cockroach:v21.1.7
#   # nodes refers to the number of crdb pods that are created
#   # via the statefulset
#   nodes: 1
#   additionalLabels:
#     crdb: us-east-1